### ISSUE TITLE
Document python coding standard

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/practices#73]
There appear to be conflicting ideas on some styling.

As a casual pythoner I'd appreciate some form of guidance.

**Comment by squidsoup** [comment]
Have you guys considered something like [Black](https://github.com/ambv/black)? Very much in the vein of adopting Prettier for js (:skull: to bikeshedding).

**Comment by nottrobin** [comment]
Just to let you know, our current policy (which isn't written down in practices yet) is that python code format should pass [flake8](http://flake8.pycqa.org/en/latest/) in its default settings (which is basically [PEP8](https://www.python.org/dev/peps/pep-0008/)). For the time being, any format differences that don't matter to `flake8` don't matter to us either, and we shouldn't bike shed about them.

But I'm just trying out Black to see if we should move our standard to be based off that instead.

**Comment by nottrobin** [comment]
After discussing with @tbille, I think maybe configuring Black to use 79 chars is better, as that's the standard in Prettier, and for Git commits etc.

**Comment by WillMoggridge** [comment]
I do have opinions on things beyond flake8 and I think strong consistency is helpful. It is nice as a maintainer and can remove doubts how to do something as a casual committer.

Black actually does all of my preferences, other than line length. Such as trailing commas and closing parenthesis on new lines. I actually enjoy the 79 character limit. [Black can be configured](https://github.com/ambv/black#pyprojecttoml) to use that line limit.

I'm fond of the line limit because it fits perfectly side by side on a 1080p monitor with a sidebar and minimaps. :)

If we use Black, it makes sense to use Black as the CI linter as well.

**Comment by WillMoggridge** [comment]
Ah yes, I concur as you can see.

**Comment by nottrobin** [comment]
@tbille also mentioned that Prettier for Python is on the way: https://github.com/prettier/prettier-python. However, since it says "WORK IN PROGRESS", I think we're probably better going with Black for now unless anyone objects?

**Comment by nottrobin** [comment]
@nkantar [mentioned](https://github.com/ambv/black/issues/498#issuecomment-418892045) [White](https://github.com/kennethreitz/white#white-black-but-brighter-pep8inspired) to me. It sounds like we should use that instead ;)

**Comment by squidsoup** [comment]
Uh oh, now the python community has a microlibrary fetish. Thanks
javascript.

**Comment by nkantar** [comment]
@nottrobin FWIW, I don't know that White is still actively maintained (or whether it needs to be). But I _was_ thinking about implementing the same thing myself, for better or worse. 😬

**Comment by nottrobin** [comment]
@nkantar I *think* I'm only joking about actually using White. Black has guides for setting it up in most editors etc., it's probably simpler for everyone, and will be less error prone, to use the original project.

**Comment by nkantar** [comment]
@nottrobin Haha, that's a relief! 👍

**Comment by b-m-f** [comment]
Added a PR => https://github.com/canonical-webteam/practices/pull/120
